### ISSUE TITLE
knife.rb location hardcoded into publish recipe

### ISSUE THREAD

**Issue by mvillis** [chef-cookbooks/delivery-truck#12]
In publish.rb there is a hardcoded link to the location of the knife.rb file.

[publish.rb](https://github.com/opscode-cookbooks/delivery-truck/blob/master/recipes/publish.rb#L25)

```
config_rb = File.join('/var/opt/delivery/workspace/.chef', 'knife.rb')
```

Can we update this reference to be an attribute? 

Happy to submit a PR just curious to know the community's preferred implementation or thoughts on this request?

**Comment by afiune** [comment]
@mvillis The main reason why this is hardcoded is because internally `delivery_build` renders this file that has the required information for delivery to manipulate the ChefServer so we can do certain tasks like: `knife cookbook upload` or `knife supermarket share`

I would love to hear from you why are you suggesting this change? Perhaps I am missing something you are trying to do and can help you achieve it in some way.. :smile:

**Comment by mvillis** [comment]
At present we have a custom delivery_build install which moves default['delivery_build']['root'] into a location different to the one defaulted to. This was to align to internal server build standards (which dictates where the preferred places are to place files and associated permissions as well as encryption requirements). This is what has triggered this chain of requests... Outside of changing our Minimum Security Baselines (possible but not necessarily something I'd chose to adventure on right now)... making this value configurable by attribute would be desirable.

**Comment by afiune** [comment]
Definitely I see the value on this. Thank you for explaining the idea! :smile: I will talk to the team to come with a solution for this use case. Will keep you posted!

**Comment by afiune** [comment]
@mvillis I think this change involve more that just a build-cookbook change. I am thinking in modifying the `delivery-cli` as well to be able to inherit the configuration. I will keep you posted of any change. Thanks for the patient :smile:

**Comment by afiune** [comment]
Last change coming. :+1:
