### ISSUE TITLE
Failure to verify metadata.rb version is updated

### ISSUE THREAD

**Issue by lcc2207** [chef-cookbooks/delivery-truck#14]
In testing I am seeing that `delivery-truck` appears to be not verifying that the `metadata.rb` version has been updated only that the file has been updated.

Example test was run:
```delivery job verify "unit lint syntax" --local```
This failed noting that the version was not updated

I added `# testing` to the `metadata.rb` leaving the version untouched.

```delivery job verify "unit lint syntax" --local```  
Then passed

**Comment by ksubrama** [comment]
Fixed with https://github.com/chef-cookbooks/delivery-truck/commit/41c479133e395a79b0faa8f109d6d51e4361568c
