### ISSUE TITLE
Enable a "root" or "Environment" security data bag

### ISSUE THREAD

**Issue by wareagl** [chef-cookbooks/delivery-truck#16]
Currently we have to create a secret databag for every project we want to sync with our Stash Git.  It would be valuable to be able to reference a single secret databag since within each project.

**Comment by afiune** [comment]
@wareagl I think this is a great enhancement but the secrets handling are coming from `delivery-sugar` so I would love if you close this issue and open it here: https://github.com/chef-cookbooks/delivery-sugar/issues
