### ISSUE TITLE
Publish fails to upload if only change is a version bump

### ISSUE THREAD

**Issue by dreamnite** [chef-cookbooks/delivery-truck#17]
If publishing to the chef server and the only change to the main cookbook is a version bump, publish does not actually upload the cookbook.

First seen while making a change to add .delivery to a new project. We bumped the version number as well (partly out of habit) and the "new" version was not uploaded to the chef server, but provision.rb did set the environment constraint. (my_cookbook = 0.1.1)

**Comment by afiune** [comment]
@dreamnite Hello! Thank you for your feedback. 

Could you please show me your `.delivery/config.json` file?

**Comment by iennae** [comment]
There have been changes in the last year. If this is still a problem for you please reopen with the additional information as requested by Salim. Thanks!
